version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile # Zakładam, że Dockerfile dla FE jest w głównym folderze
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile # Zakładam, że Dockerfile dla BE znajduje się w folderze /api
    ports:
      - "5000:5000"
    environment:
      - DATABASE_HOST=mariadb
      - MARIADB_DATABASE=${MYSQL_DATABASE}
      - MARIADB_USER=${MYSQL_USER}
      - MARIADB_PASSWORD=${MYSQL_PASSWORD}
      - DATABASE_PORT=${DATABASE_PORT}
      - CORS=${CORS}
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MYSQL_DATABASE}
      - MARIADB_USER=${MYSQL_USER}
      - MARIADB_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
